name = "magistral-small-2509"
description = "Magistral Small 2509 is a 24B-parameter open-weight reasoning model with vision support, offering a 15% performance boost and improved multimodal reasoning over its predecessor."
release_date = "2025-09-18"
last_updated = "2025-09-18"
attachment = true
reasoning = true
temperature = false
tool_call = true
structured_output = true
open_weights = false
reasoning_options = []

[cost]
input = 0.557
output = 1.671
cache_read = 0.056

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
